name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Validate manifest.json
      run: npm run validate

    - name: Check for required files
      run: |
        echo "Checking for required Chrome extension files..."
        test -f manifest.json && echo "✓ manifest.json found"
        test -f background.js && echo "✓ background.js found"
        test -f popup.html && echo "✓ popup.html found"
        test -f popup.js && echo "✓ popup.js found"
        test -d icons && echo "✓ icons directory found"
        echo "All required files present!"
